language: php

php:
  - 5.6.5
  - 7.0.2
  - 7.0.4
  - 7.0.6
  - hhvm

script:
  - git clone https://github.com/squizlabs/PHP_CodeSniffer.git phpcs
  - git clone https://github.com/magento/marketplace-eqp.git eqp
  - phpcs/scripts/phpcs --config-set installed_paths eqp
  - phpcs/scripts/phpcs --ignore=phpcs,eqp --standard=MEQP2 .
  - zip -r botamp_botamp-1.0.0.zip . -x '.git/*' 'phpcs/*' 'eqp/*'
  - git clone https://github.com/magento/marketplace-tools.git validator
  - php validator/validate_m2_package.php botamp_botamp-1.0.0.zip
